🚀 4단계 - Controller 메서드 인자 매핑
next-step/java-mvc pull request #60
Opened 2024-08-15 07:52 UTC by jivebreaddev

## 테스트
![image](https://github.com/user-attachments/assets/8da4a579-37d3-4c76-ac32-70fb8ff643f2)

## 요구사항

[x] 학습 테스트를 
[x] Controller 메서드의 인자 타입에 따라 자동 으로 형변환 후 맵핑
    - [x] compilerArgs 옵션을 생성해서 메서드 파라미터를 가져올 수 있게 적용합니다.
    - [x] HandlerMethodArgumentResolver에 기능 추가를 합니다.
        - Resolvers들을 Registry 형태로 생성합니다.
            - primitive type에 대한 지원을 추가합니다.
            - 객체 타입에 대한 지원을 추가합니다.
            - 기본적인 Wrapper class에 대한 지원을 추가합니다.
            - HttpServletRequest와 HttpServletResponse를 지원한다.
    - [x] PathPatternParser를 이용해서 PathVariable 구현을 위한 기능을 추가합니다.
        - 기능
            - URL 매칭과 경로에서 변수를 추출한다.
        - 조건
            - "/users/{id}"
            - "/users/{id}/otherResource/{resourceId}" 와 같은 포맷을 지원한다.
    - [x] Resolver를 MethodMapping 할때, 알맞은 args를 넘겨주도록 사용합니다.

선흠님 이번에도 잘 부탁드리겠습니다!

2024-08-15 16:53 UTC, shared-moon requested changes
시창님 안녕하세요!
4단계 미션 잘 진행 해 주셨네요 :)
한번 다시 보면 좋을 것 같아서 코멘트를 좀 남겨뒀는데, 확인 후 리뷰 재요청 부탁드려요!
고생 많으셨습니다 :)

2024-08-15 16:53 UTC, shared-moon commented on mvc/src/main/java/com/interface21/webmvc/servlet/mvc/tobe/HandlerExecution.java
> +    private Map<Method, Object[]> args = new HashMap<>();
이름이 맵이라는게 안드러나서 좀 헷갈리는거 같아요 ~ argumentsByMethod 같은 이름은 어떨까요 ?

2024-08-15 16:53 UTC, shared-moon commented on mvc/src/main/java/com/interface21/webmvc/servlet/mvc/tobe/HandlerExecution.java
> +    private void initializeArgs(HttpServletRequest request, HttpServletResponse response) {
구조가 조금 헷갈리는데 .. HandlerExecution이 지금 Controller의 method + endpoint 마다 하나씩 생기는게 맞을까요 ?
그렇다면 args가 맵이어야 할 이유가 없어보여서 여쭤봅니다 ~

2024-08-15 16:53 UTC, shared-moon commented on mvc/src/main/java/com/interface21/webmvc/servlet/mvc/tobe/meta/ControllerScanner.java
> +                        .forEach(key -> acc.put(key, new HandlerExecution(instance, method, resolverRegistry.addResolver(controllerUri)))),
요거 마지막에 resolver가 계속 add 될 이유가 있을까요 ? registry에는 타입별로 한번씩만 들어가있으면 될 것 같아서요!

2024-08-15 16:53 UTC, shared-moon commented on mvc/src/main/java/com/interface21/webmvc/servlet/mvc/tobe/meta/ControllerScanner.java
> +                .orElse(null);
요거 null로 넘기는게 아니라 없으면 예외가 발생해야 하는 거 아닐까요 ?

2024-08-15 16:53 UTC, shared-moon commented on mvc/src/main/java/com/interface21/webmvc/servlet/mvc/tobe/parameter/TypeMapper.java
> +    public static void createTypeToParser() {
요거 Map.of를 통해 초기화하면 null체크 등등 작업이 필요 없을 수도 있을 것 같아요!

2024-08-17 05:02 UTC, jivebreaddev commented on mvc/src/main/java/com/interface21/webmvc/servlet/mvc/tobe/HandlerExecution.java
> +    private void initializeArgs(HttpServletRequest request, HttpServletResponse response) {
HandlerExecution은 method+ endpoint 마다 한개씩 생기게 되고 parameter에 대한 Resolving의 결과는 캐싱 처리 하려고 했습니다.

말씀하신대로, 변수이름도 이상하고, 맵일 필요없어서 변경하였습니다!

2024-08-17 05:03 UTC, jivebreaddev commented on mvc/src/main/java/com/interface21/webmvc/servlet/mvc/tobe/HandlerExecution.java
> +    private Map<Method, Object[]> args = new HashMap<>();
`resolvedParamters` 로 변경하였습니다!

명명법에 신경을 못써서 가독성에 문제를 줬군요;;

좋은 리뷰 감사합니다!

2024-08-17 05:10 UTC, jivebreaddev commented on mvc/src/main/java/com/interface21/webmvc/servlet/mvc/tobe/meta/ControllerScanner.java
> +                        .forEach(key -> acc.put(key, new HandlerExecution(instance, method, resolverRegistry.addResolver(controllerUri)))),
PathVariableResolver에만 추가하는 방향으로 변경하겠습니다.

2024-08-17 05:33 UTC, jivebreaddev commented on mvc/src/main/java/com/interface21/webmvc/servlet/mvc/tobe/meta/ControllerScanner.java
> +                .orElse(null);
![image](https://github.com/user-attachments/assets/acd754dc-2ad3-4abc-9940-49885463f8dc)

클라이언트에서 exception을 핸들링 하게끔 한것인데 생각해보니깐, 라이브러리 코드로 다른 분들이 해당 코드를 사용할때, 오해가 생길 수 있을것같네요!!
좋은방향의 코드 수정인것 같습니다.

2024-08-17 05:37 UTC, jivebreaddev commented on mvc/src/main/java/com/interface21/webmvc/servlet/mvc/tobe/parameter/TypeMapper.java
> +    public static void createTypeToParser() {
그렇군요!!
final 과 immutable map의 사용으로, 훨씬 안전한 코드가 될 수 있겠네요!

run time에 수정할 수도 있지 않을까해서 열어놨는데 immuatble로 수정했습니다.

2024-08-18 00:44 UTC, shared-moon approved these changes
시창님 안녕하세요!
피드백 반영 잘 해 주셨네요 :)
작은 코멘트 하나만 남겨뒀는데 나중에 확인 부탁드려요!
미션은 이만 머지 하도록 하겠습니다.
나머지 미션도 화이팅 하세요 🔥 
고생 많으셨습니다!

2024-08-18 00:44 UTC, shared-moon commented on mvc/src/main/java/com/interface21/webmvc/servlet/mvc/tobe/HandlerExecution.java
> +        if (Objects.nonNull(resolvedParamters)) {
nonNull이랑 isEmpty는 조금 다른 내용일텐데 의도하신게 맞을까요 ?

2024-08-18 00:44 UTC, merged